# Generated by Django 6.1.2 on 2026-10-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('aprovada', 'Aprovada'), ('execucao', 'Em execução'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='orcamento', max_length=10)),
                ('defeito_relatado', models.TextField(verbose_name='Defeito relatado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('km_entrada', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM entrada')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('estoque_baixado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='Código')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de venda')),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque mínimo')),
            ],
            options={
                'verbose_name': 'Peça',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='PecaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço unitário')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='oficina.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficina.peca')),
            ],
            options={
                'verbose_name': 'Peça utilizada',
                'verbose_name_plural': 'Peças utilizadas',
            },
        ),
        migrations.CreateModel(
            name='ServicoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='oficina.ordemservico')),
            ],
            options={
                'verbose_name': 'Serviço',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('caminhao', 'Caminhão'), ('onibus', 'Ônibus'), ('moto', 'Moto'), ('outro', 'Outro')], default='carro', max_length=10)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=80)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('tensao', models.CharField(choices=[('12V', '12V'), ('24V', '24V')], default='12V', max_length=5, verbose_name='Tensão')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='oficina.cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.veiculo'),
        ),
    ]
